"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import SiteNav from "@/components/SiteNav";
import { useI18n } from "@/components/LanguageProvider";
import { message } from "@/lib/i18n";

export default function LoginPage() { const router = useRouter(); const { d } = useI18n(); const user = useAuth(); const [busy, setBusy] = useState(false); const [mode, setMode] = useState<"login" | "register">("login"); const [studentId, setStudentId] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const response = await fetch("/api/auth", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, studentId, name, password }) }); const data = await response.json(); if (!response.ok) { setError(message(d, data.error)); return; } router.push("/my-reports"); router.refresh(); } catch { setError(message(d, "ระบบขัดข้อง กรุณาลองใหม่อีกครั้ง")); } finally { setBusy(false); } } async function logout() { await fetch("/api/auth", { method: "DELETE" }); router.refresh(); } return <div className="shell"><SiteNav /><main><section className="page-hero"><div className="wrap narrow"><div className="eyebrow">{d.login.eyebrow}</div><h1>{mode === "login" ? d.login.loginTitle : d.login.registerTitle}</h1></div></section><div className="container form-layout">{user ? <div className="form-panel"><p>{user.name} ({user.studentId})</p><button className="primary" type="button" onClick={() => router.push("/my-reports")}>{d.nav.mine}</button><button className="text-button" type="button" onClick={logout}>{d.login.logout}</button></div> : <form className="form-panel" onSubmit={submit}>{mode === "register" && <div className="field"><label>{d.login.name}</label><input value={name} onChange={(event) => setName(event.target.value)} required /></div>}<div className="field"><label>{d.login.studentId}</label><input value={studentId} onChange={(event) => setStudentId(event.target.value)} required /></div><div className="field"><label>{d.login.password}</label><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={6} /></div>{error && <p className="form-error">{error}</p>}<button className="primary" type="submit" disabled={busy}>{mode === "login" ? d.login.loginButton : d.login.registerButton}</button><button className="text-button" type="button" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? d.login.toRegister : d.login.toLogin}</button></form>}</div></main></div>; }
